name: Generate and Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          pip3 install --break-system-packages coverxygen

      - name: Generate docs
        uses: mattnotmitt/doxygen-action@v1.12.0
        with:
          doxyfile-path: 'Doxyfile'

      - name: Generate coverage report
        run: |
          mkdir -p extra/docs
          python3 -m coverxygen --xml-dir docs/xml --src-dir . --format markdown-summary --output extra/docs/coverage.md

      - name: Generate docs with extra page
        uses: mattnotmitt/doxygen-action@v1.12.0
        with:
          doxyfile-path: 'Doxyfile'

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/
          publish_branch: gh-pages

permissions:
  contents: write
